#!/bin/sh
cat > /lib/svc/method/OZopensshd <<'EOF'
#!/sbin/sh
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

. /lib/svc/share/ipf_include.sh

SSHDIR=/opt/oz/etc
KEYGEN="/opt/oz/bin/ssh-keygen"
PIDFILE=/var/run/OZopensshd.pid

# Checks to see if RSA, and DSA host keys are available
# if any of these keys are not present, the respective keys are created.
create_key()
{
	keypath=$1
	keytype=$2

	if [ ! -f $keypath ]; then
#		grep "^HostKey $keypath" $SSHDIR/sshd_config > /dev/null 2>&1
#		if [ $? -eq 0 ]; then
			echo Creating new $keytype public/private host key pair
			$KEYGEN -f $keypath -t $keytype -N ''
			return $?
#		fi
	fi

	return 0
}

create_ipf_rules()
{
	FMRI=$1
	ipf_file=`fmri_to_file ${FMRI} $IPF_SUFFIX`
	policy=`get_policy ${FMRI}`

	tports=`grep "^Port" /opt/oz/etc/sshd_config 2>/dev/null | \
	    awk '{print $2}'`

	echo "# $FMRI" >$ipf_file
	for port in $tports; do
		generate_rules $FMRI $policy "tcp" "any" $port $ipf_file
	done
}

# This script is being used for two purposes: as part of an SMF
# start/stop/refresh method, and as a sysidconfig(1M)/sys-unconfig(1M)
# application.
#
# Both, the SMF methods and sysidconfig/sys-unconfig use different
# arguments..

case $1 in 
	# sysidconfig/sys-unconfig arguments (-c and -u)
'-c')
	create_key $SSHDIR/ssh_host_rsa_key rsa
	create_key $SSHDIR/ssh_host_ed25519_key ed25519
	;;

'-u')
	# sys-unconfig(1M) knows how to remove ssh host keys, so there's
	# nothing to do here.
	:
	;;

	# SMF arguments (start and restart [really "refresh"])

'ipfilter')
	create_ipf_rules $2
	;;

'start')
	if [ -f /.livecd ] && [ ! -f $SSHDIR/ssh_host_rsa_key ]; then
		create_key $SSHDIR/ssh_host_rsa_key rsa
		create_key $SSHDIR/ssh_host_ed25519_key ed25519
	fi
	/opt/oz/sbin/sshd -h $SSHDIR/ssh_host_rsa_key -h $SSHDIR/ssh_host_ed25519_key
	;;

'restart')
	if [ -f "$PIDFILE" ]; then
		/usr/bin/kill -HUP `/usr/bin/cat $PIDFILE`
	fi
	;;

*)
	echo "Usage: $0 { start | restart }"
	exit 1
	;;
esac	

exit $?
EOF

cat > /var/svc/manifest/ozopensshd.xml <<'EOF'
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<!--
	CDDL HEADER START

	The contents of this file are subject to the terms of the
	Common Development and Distribution License (the "License").
	You may not use this file except in compliance with the License.

	You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
	or http://www.opensolaris.org/os/licensing.
	See the License for the specific language governing permissions
	and limitations under the License.

	When distributing Covered Code, include this CDDL HEADER in each
	file and include the License file at usr/src/OPENSOLARIS.LICENSE.
	If applicable, add the following below this CDDL HEADER, with the
	fields enclosed by brackets "[]" replaced with your own identifying
	information: Portions Copyright [yyyy] [name of copyright owner]

	CDDL HEADER END

	Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
	Use is subject to license terms.

	NOTE:  This service manifest is not editable; its contents will
	be overwritten by package or patch operations, including
	operating system upgrade.  Make customizations in a different
	file.
-->

<service_bundle type='manifest' name='OZopenssh:ssh'>

<service
	name='ozopenssh'
	type='service'
	version='1'>

	<create_default_instance enabled='false' />

	<single_instance />

	<dependency name='fs-local'
		grouping='require_all'
		restart_on='none'
		type='service'>
		<service_fmri
			value='svc:/system/filesystem/local' />
	</dependency>

	<dependency name='fs-autofs'
		grouping='optional_all'
		restart_on='none'
		type='service'>
		<service_fmri value='svc:/system/filesystem/autofs' />
	</dependency>

	<dependency name='net-loopback'
		grouping='require_all'
		restart_on='none'
		type='service'>
		<service_fmri value='svc:/network/loopback' />
	</dependency>

	<dependency name='net-physical'
		grouping='require_all'
		restart_on='none'
		type='service'>
		<service_fmri value='svc:/network/physical' />
	</dependency>

	<dependency name='cryptosvc'
		grouping='require_all'
		restart_on='none'
		type='service'>
		<service_fmri value='svc:/system/cryptosvc' />
	</dependency>

	<dependency name='utmp'
		grouping='require_all'
		restart_on='none'
		type='service'>
		<service_fmri value='svc:/system/utmp' />
	</dependency>

	<dependency name='network_ipfilter'
		grouping='optional_all'
		restart_on='error'
		type='service'>
		<service_fmri value='svc:/network/ipfilter:default' />
	</dependency>

	<dependency name='config_data'
		grouping='require_all'
		restart_on='restart'
		type='path'>
		<service_fmri
		    value='file://localhost/opt/oz/etc/sshd_config' />
	</dependency>

	<dependent
		name='ssh_multi-user-server'
		grouping='optional_all'
		restart_on='none'>
			<service_fmri
			    value='svc:/milestone/multi-user-server' />
	</dependent>

	<exec_method
		type='method'
		name='start'
		exec='/lib/svc/method/OZopensshd start'
		timeout_seconds='60'/>

	<exec_method
		type='method'
		name='stop'
		exec=':kill'
		timeout_seconds='60' />

	<exec_method
		type='method'
		name='refresh'
		exec='/lib/svc/method/OZopensshd restart'
		timeout_seconds='60' />

	<property_group name='startd'
		type='framework'>
		<!-- sub-process core dumps shouldn't restart session -->
		<propval name='ignore_error'
		    type='astring' value='core,signal' />
	</property_group>

        <property_group name='general' type='framework'>
                <!-- to start stop sshd -->
                <propval name='action_authorization' type='astring'
                        value='solaris.smf.manage.ssh' />
        </property_group>

	<property_group name='firewall_context' type='com.sun,fw_definition'>
		<propval name='name' type='astring' value='ssh' />
		<propval name='ipf_method' type='astring'
		    value='/lib/svc/method/OZopensshd ipfilter' />
	</property_group>

	<property_group name='firewall_config' type='com.sun,fw_configuration'>
		<propval name='policy' type='astring' value='use_global' />
		<propval name='apply_to' type='astring' value='' />
		<propval name='exceptions' type='astring' value='' />
		<propval name='value_authorization' type='astring'
			value='solaris.smf.value.firewall.config' />
	</property_group>

	<stability value='Unstable' />

	<template>
		<common_name>
			<loctext xml:lang='C'>
			SSH server
			</loctext>
		</common_name>
		<documentation>
			<manpage title='sshd' section='8' manpath='/opt/OZ/share/man' />
		</documentation>
	</template>

</service>

</service_bundle>
EOF

chmod +x /lib/svc/method/OZopensshd

echo "If you see warnings about user/group sshd already existing, ignore them."
groupadd -g 43 sshd
useradd -u 43 -g 43 -c sshd -d / sshd

echo ""

# Reload SMF so it sees the new manifest
if [ -x /usr/sbin/svccfg ]; then
    /usr/sbin/svccfg import /var/svc/manifest/ozopensshd.xml 2>/dev/null || true
fi

if [ -x /usr/sbin/svcadm ]; then
    /usr/sbin/svcadm refresh ozopensshd 2>/dev/null || true
fi

/lib/svc/method/OZopensshd -c
echo "You may need to import the service at /var/svc/manifest/ozopensshd.xml."


